//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Managment.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ExamClassSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamClassSubject()
        {
            this.ExamsStudents = new HashSet<ExamsStudents>();
        }
    
        public Guid Id { get; set; }
        public Guid ExamId { get; set; }
        public Guid SubjectClassId { get; set; }
        public DateTime ExamDate { get; set; }
    
        [ForeignKey("ExamId")]
        public virtual Exams Exam { get; set; }
        [ForeignKey("SubjectClassId")]
        public virtual ClassSubject ClassSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamsStudents> ExamsStudents { get; set; }
    }
}
