//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broadway.DesktopApp.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Broadway_430Entities : DbContext
    {
        public Broadway_430Entities()
            : base("name=Broadway_430Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentNew> StudentNews { get; set; }
        public virtual DbSet<Sudhan> Sudhans { get; set; }
        public virtual DbSet<ParenView> ParenViews { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentParent> StudentParents { get; set; }
        public virtual DbSet<ParentAddress> ParentAddresses { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    
        public virtual ObjectResult<SP_StudentParent_Result> SP_StudentParent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_StudentParent_Result>("SP_StudentParent");
        }
    }
}
