//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broadway.DesktopApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParenView
    {
        public int id { get; set; }
        public string name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
    }
}
