//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broadway.DesktopApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentParent
    {
        public int Id { get; set; }
        public string ParentName { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ParentType { get; set; }
    }
}
