//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Managment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicYear()
        {
            this.Subjects = new HashSet<Subject>();
            this.Classes = new HashSet<Classes>();
            this.Attendances = new HashSet<Attendance>();
            this.Exams = new HashSet<Exams>();
        }
    
        public Guid Id { get; set; }
        public string YearName { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public bool IsActive { get; set; }
    

        public virtual ICollection<Subject> Subjects { get; set; }

        public virtual ICollection<Classes> Classes { get; set; }

        public virtual ICollection<Attendance> Attendances { get; set; }

        public virtual ICollection<Exams> Exams { get; set; }
    }
}
