//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Managment.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Classes
    {
        public Classes()
        {
            this.ClassSubjects = new HashSet<ClassSubject>();
            this.StudentClasses = new HashSet<StudentClass>();
        }
    
        public Guid Id { get; set; }
        public string ClassName { get; set; }
        public string RoomNumber { get; set; }
        public Guid ClassTeacherId { get; set; }
        public Guid AcademicYearId { get; set; }
        public bool IsActive { get; set; }
    

        public virtual ICollection<ClassSubject> ClassSubjects { get; set; }

        public virtual ICollection<StudentClass> StudentClasses { get; set; }

        [ForeignKey("ClassTeacherId")]
        public virtual Teacher Teacher { get; set; }
        [ForeignKey("AcademicYearId")]
        public virtual AcademicYear AcademicYear { get; set; }
    }
}
