//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Managment.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ExamsStudents
    {
        public Guid Id { get; set; }
        public Guid StudentId { get; set; }
        public Guid ExamDetailsId { get; set; }
        public string MarksObtained { get; set; }
        public string FullMarks { get; set; }
        public string PassMarks { get; set; }
        public string ExamType { get; set; }
        public string AttendanceStatus { get; set; }
    
        [ForeignKey("StudentId")]
        public virtual Student Student { get; set; }
        [ForeignKey("ExamDetailsId")]
        public virtual ExamClassSubject ExamClassSubject { get; set; }
    }
}
